<a href="https://colab.research.google.com/github/abhinandan-084/pytorch-tutorials/blob/main/01_PyTorch_Intros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Base Libraries

In [19]:
## Standard libraries
import os
import math
import numpy as np
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

/tmp/ipykernel_346/47578708.py:11: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


## 2. Torch Basics

In [20]:
import torch
print("Using torch", torch.__version__)

Using torch 2.10.0+cu128


In [21]:
# Reproducible Random Numbers
torch.manual_seed(42) # Setting the seed

## 3. Tensors

### 3.1 Initialization

The function **torch.Tensor** allocates memory for the desired tensor, but reuses any values that have already been in the memory. To directly assign values to the tensor during initialization, there are many alternatives including:

* **torch.zeros**: Creates a tensor filled with zeros
* **torch.ones**: Creates a tensor filled with ones
* **torch.rand**: Creates a tensor with random values uniformly sampled between 0 and 1
* **torch.randn**: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
* **torch.arange**: Creates a tensor containing the values
* **torch.Tensor (input list)**: Creates a tensor from the list elements you provide



In [22]:
x = torch.Tensor(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[2.0686e+00, 0.0000e+00, 2.0685e+00, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
         [1.7867e+00, 0.0000e+00, 8.9683e-44, 0.0000e+00]],

        [[2.0069e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.1351e-43, 0.0000e+00]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [23]:
x = torch.zeros(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [24]:
x = torch.ones(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [25]:
x = torch.rand(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [26]:
x = torch.randn(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[ 0.3559, -0.6866, -0.4934,  0.2415],
         [-1.1109,  0.0915, -2.3169, -0.2168],
         [-0.9138, -0.6581,  0.0780,  0.5258]],

        [[-0.4880,  1.1914, -0.8140, -0.7360],
         [-1.4032,  0.0360, -0.0635,  0.6756],
         [-0.0978,  1.8446, -1.1845,  1.3835]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [27]:
x = torch.arange(2, 10, 2) # This will create a tensor with values [2, 4, 6, 8]
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)

tensor([2, 4, 6, 8])

Shape: torch.Size([4])
Size: torch.Size([4])


In [28]:
# Create a tensor from a (nested) list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2  = x.size()
print("Size:", dim1, dim2)

tensor([[1., 2.],
        [3., 4.]])

Shape: torch.Size([2, 2])
Size: torch.Size([2, 2])
Size: 2 2


### 3.2 Tensor to Numpy, and Numpy to Tensor

Tensors can be converted to numpy arrays, and numpy arrays back to tensors. To transform a numpy array into a tensor, we can use the function torch.from_numpy. To transform a PyTorch tensor back to a numpy array, we can use the function .numpy() on tensors.

The conversion of tensors to numpy require the tensor to be on the CPU, and not the GPU (more on GPU support in a later section). In case you have a tensor on GPU, you need to call .cpu() on the tensor beforehand. Hence, you get a line like np_arr = tensor.cpu().numpy()

In [29]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [30]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]
