<a href="https://colab.research.google.com/github/abhinandan-084/pytorch-tutorials/blob/main/01_PyTorch_Intros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Base Libraries

In [24]:
## Standard libraries
import os
import math
import numpy as np
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

/tmp/ipykernel_2578/47578708.py:11: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


## 2. Torch Basics

In [25]:
import torch
print("Using torch", torch.__version__)

Using torch 2.10.0+cu128


In [26]:
# Reproducible Random Numbers
torch.manual_seed(42) # Setting the seed

## 3. Tensors

### 3.1 Initialization

The function **torch.Tensor** allocates memory for the desired tensor, but reuses any values that have already been in the memory. To directly assign values to the tensor during initialization, there are many alternatives including:

* **torch.zeros**: Creates a tensor filled with zeros
* **torch.ones**: Creates a tensor filled with ones
* **torch.rand**: Creates a tensor with random values uniformly sampled between 0 and 1
* **torch.randn**: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
* **torch.arange**: Creates a tensor containing the values
* **torch.Tensor (input list)**: Creates a tensor from the list elements you provide



In [27]:
x = torch.Tensor(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[2.1715e-18, 1.6613e-07, 6.7507e-07, 6.7505e-07],
         [1.6803e-04, 1.6778e+22, 5.3133e-08, 4.2235e-08],
         [1.6411e-07, 6.6449e-07, 1.2993e-08, 2.3050e-12]],

        [[1.8788e+31, 7.9303e+34, 6.1949e-04, 1.8590e+34],
         [7.7767e+31, 7.1536e+22, 3.3803e-18, 2.0552e+32],
         [1.8755e+28, 3.1093e-18, 2.0552e+32, 1.8755e+28]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [28]:
x = torch.zeros(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [29]:
x = torch.ones(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [30]:
x = torch.rand(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [31]:
x = torch.randn(2, 3, 4)
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

tensor([[[ 0.3559, -0.6866, -0.4934,  0.2415],
         [-1.1109,  0.0915, -2.3169, -0.2168],
         [-0.9138, -0.6581,  0.0780,  0.5258]],

        [[-0.4880,  1.1914, -0.8140, -0.7360],
         [-1.4032,  0.0360, -0.0635,  0.6756],
         [-0.0978,  1.8446, -1.1845,  1.3835]]])

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [32]:
x = torch.arange(2, 10, 2) # This will create a tensor with values [2, 4, 6, 8]
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)

tensor([2, 4, 6, 8])

Shape: torch.Size([4])
Size: torch.Size([4])


In [33]:
# Create a tensor from a (nested) list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

shape = x.shape
print("\nShape:", x.shape)
size = x.size()
print("Size:", size)
dim1, dim2  = x.size()
print("Size:", dim1, dim2)

tensor([[1., 2.],
        [3., 4.]])

Shape: torch.Size([2, 2])
Size: torch.Size([2, 2])
Size: 2 2


### 3.2 Tensor to Numpy, and Numpy to Tensor

Tensors can be converted to numpy arrays, and numpy arrays back to tensors. To transform a numpy array into a tensor, we can use the function torch.from_numpy. To transform a PyTorch tensor back to a numpy array, we can use the function .numpy() on tensors.

**The conversion of tensors to numpy require the tensor to be on the CPU, and not the GPU (more on GPU support in a later section). In case you have a tensor on GPU, you need to call .cpu() on the tensor beforehand. Hence, you get a line like np_arr = tensor.cpu().numpy()**

In [34]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [35]:
 tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


### 3.3 Operations

The simplest operation is to add two tensors:

In [36]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018]])
X2 tensor([[0.9497, 0.6666, 0.9811],
        [0.0874, 0.0041, 0.1088]])
Y tensor([[1.6029, 1.0625, 1.8958],
        [0.2910, 0.2059, 0.3106]])


Calling x1 + x2 creates a new tensor containing the sum of the two inputs. However, we can also use in-place operations that are applied directly on the memory of a tensor. We therefore change the values of x2 without the chance to re-accessing the values of x2 before the operation. In-place operations are usually marked with a underscore postfix (e.g. “add_” instead of “add”). An example is shown below:

In [37]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.1637, 0.7025, 0.6790],
        [0.9155, 0.2418, 0.1591]])
X2 (before) tensor([[0.7653, 0.2979, 0.8035],
        [0.3813, 0.7860, 0.1115]])
X1 (after) tensor([[0.1637, 0.7025, 0.6790],
        [0.9155, 0.2418, 0.1591]])
X2 (after) tensor([[0.9289, 1.0004, 1.4825],
        [1.2968, 1.0278, 0.2707]])


Another common operation aims at changing the shape of a tensor. A tensor of size (2,3) can be re-organized to any other shape with the same number of elements (e.g. a tensor of size (6), or (3,2), …). In PyTorch, this operation is called view:

In [38]:
x = torch.arange(6)
print("X", x)

x = x.view(2, 3)
print("X", x)

x = x.permute(1, 0) # Swapping dimension 0 and 1
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])
X tensor([[0, 1, 2],
        [3, 4, 5]])
X tensor([[0, 3],
        [1, 4],
        [2, 5]])


Other commonly used operations include matrix multiplications, which are essential for neural networks. Quite often, we have an input vector X, which is transformed using a learned weight matrix. There are multiple ways and functions to perform matrix multiplication, some of which we list below:

* **torch.matmul**: Performs the matrix product over two tensors, where the specific behavior depends on the dimensions. If both inputs are matrices (2-dimensional tensors), it performs the standard matrix product. For higher dimensional inputs, the function supports broadcasting. Can also be written as a @ b, similar to numpy.

* **torch.mm**: Performs the matrix product over two matrices, but doesn’t support broadcasting

* **torch.bmm**: Performs the matrix product with a support batch dimension. If the first tensor **T is of shape (bXnXm)**, and the second tensor **R(bXmXp)**, the output **O is of shape (bXnXp)**, and has been calculated by performing b matrix multiplications of the submatrices of **T** and **R**

* **torch.einsum**: Performs matrix multiplications and more (i.e. sums of products) using the Einstein summation convention

In [39]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

h = torch.matmul(x, W) # Verify the result by calculating it by hand too!
print("h", h)

X tensor([[0, 1, 2],
        [3, 4, 5]])
W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
h tensor([[15, 18, 21],
        [42, 54, 66]])


### 3.4 Indexing

We often have the situation where we need to select a part of a tensor. Indexing works just like in numpy

In [40]:
x = torch.arange(12).view(3, 4)
print("X", x)
print(x[:, 1])   # Second column
print(x[0])      # First row
print(x[:2, -1]) # First two rows, last column
print(x[1:3, :]) # Middle two rows

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([1, 5, 9])
tensor([0, 1, 2, 3])
tensor([3, 7])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


### 3.5 Dynamic Computation Graph and Backpropagation

Given an input X, we define our function by manipulating that input, usually by matrix-multiplications with weight matrices and additions with so-called bias vectors. As we manipulate our input, we are automatically creating a computational graph. This graph shows how to arrive at our output from our input. PyTorch is a define-by-run framework; this means that we can just do our manipulations, and PyTorch will keep track of that graph for us. Thus, we create a dynamic computation graph along the way.

So, to recap: the only thing we have to do is to compute the output, and then we can ask PyTorch to automatically get the gradients.

**Note: Why do we want gradients?** Consider that we have defined a function, a neural net, that is supposed to compute a certain output **Y** for an input vector **X**. We then define an error measure that tells us how wrong our network is; how bad it is in predicting output **Y** from input **X**. Based on this error measure, we can use the gradients to **update** the weights **W** that were responsible for the output, so that the next time we present input **X** to our network, the output will be closer to what we want.

The first thing we have to do is to specify which tensors require gradients. By default, when we create a tensor, it does not require gradients. We can change this for an existing tensor using the function requires_grad_() (underscore indicating that this is a in-place operation). Alternatively, when creating a tensor, you can pass the argument requires_grad=True to most initializers we have seen above.

y = \frac{1}{\ell(x)}\sum_i \left[(x_i + 2)^2 + 3\right],



In [41]:
x = torch.ones((3,))
print(x.requires_grad)

x.requires_grad_(True)
print(x.requires_grad)

x = torch.arange(3, dtype=torch.float32, requires_grad=True) # Only float tensors can have gradients
print("X: ", x)

False
True
X:  tensor([0., 1., 2.], requires_grad=True)


Now let's build the computation graph step by step. You can combine multiple operations in a single line, but we will separate them here to get a better understanding of how each operation is added to the computation graph.

We can perform backpropagation on the computation graph by calling the function ***backward()*** on the last output, which effectively calculates the gradients for each tensor that has the property requires_grad=True

In [42]:
a = x + 2
b = a ** 2
c = b + 3
y = c.mean()
print("Y", y)

Y tensor(12.6667, grad_fn=<MeanBackward0>)


In [43]:
y.backward()
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


### 3.6 GPU support


By default, all tensors you create are stored on the CPU. We can push a tensor to the GPU by using the function .to(...), or .cuda(). However, it is often a good practice to define a device object in your code which points to the GPU if you have one, and otherwise to the CPU. Then, you can write your code with respect to this device object, and it allows you to run the same code on both a CPU-only system, and one with a GPU. Let's try it below. We can specify the device as follows:

In [44]:
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

x = torch.zeros(2, 3)
x = x.to(device)
print("X", x)

Is the GPU available? True
Device cuda
X tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


Let's compare the runtime of a large matrix multiplication on the CPU with a operation on the GPU:

In [45]:
x = torch.randn(5000, 5000)

## CPU version
start_time = time.time()
_ = torch.matmul(x, x)
end_time = time.time()
print(f"CPU time: {(end_time - start_time):6.5f}s")

## GPU version
x = x.to(device)
_ = torch.matmul(x, x)  # First operation to 'burn in' GPU
# CUDA is asynchronous, so we need to use different timing functions
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)
start.record()
_ = torch.matmul(x, x)
end.record()
torch.cuda.synchronize()  # Waits for everything to finish running on the GPU
print(f"GPU time: {0.001 * start.elapsed_time(end):6.5f}s")  # Milliseconds to seconds

CPU time: 2.92999s
GPU time: 0.08335s


When generating random numbers, the seed between CPU and GPU is not synchronized. Hence, we need to set the seed on the GPU separately to ensure a reproducible code. Note that due to different GPU architectures, running the same code on different GPUs does not guarantee the same random numbers. Still, we don't want that our code gives us a different output every time we run it on the exact same hardware. Hence, we also set the seed on the GPU:

In [46]:
# GPU operations have a separate seed we also want to set
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)

# Additionally, some operations on a GPU are implemented stochastic for efficiency
# We want to ensure that all operations are deterministic on GPU (if used) for reproducibility
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False